
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Mon Jul 18 17:02:12 CEST 2016
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int PIPE = 14;
  public static final int PLUS = 12;
  public static final int INT = 19;
  public static final int ALL = 22;
  public static final int S = 4;
  public static final int RO = 6;
  public static final int END = 17;
  public static final int ODD = 20;
  public static final int ID = 18;
  public static final int GO = 10;
  public static final int RC = 7;
  public static final int SO = 8;
  public static final int EOF = 0;
  public static final int C = 5;
  public static final int EVEN = 21;
  public static final int MINUS = 13;
  public static final int error = 1;
  public static final int DOT = 3;
  public static final int GC = 11;
  public static final int EQ = 2;
  public static final int SC = 9;
  public static final int MUL = 15;
  public static final int NL = 16;
}
